#%RAML 1.0
version: 1.0
title: hanuma-greetings-api
baseUri: http://localhost:8081/v1/
/greetings:
  post:
    body:
      application/json:
        properties:
          name:
            type: string
            required: true
    responses:
      200:
        body:
          application/json:
            example:
              {
                "result" : "hello hanuma"
              }    